CREATE SCHEMA STARSHIP_BI
GO


/*/// CREACIÓN DE DIMENSIONES ///////////////////////////////////////// */
/*
CREATE TABLE STARSHIP_BI.DIMENSION_ (

);
*/

CREATE TABLE STARSHIP_BI.DIMENSION_TIEMPO (
    TIEMPO_ID DECIMAL(19,0) IDENTITY(1,1), --- PK
    TIEMPO_ANIO DECIMAL(19,0),
	TIEMPO_MES DECIMAL(19,0),
	CONSTRAINT PK_DIMENSION_TIEMPO PRIMARY KEY (TIEMPO_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_DIA (
    DIA_ID DECIMAL(19,0), --- PK --- DB
    DIA_DETALLE NVARCHAR(50),
	CONSTRAINT PK_DIMENSION_DIA PRIMARY KEY (DIA_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_RANGO_HORARIO (
    RANGO_HORARIO_ID DECIMAL(19,0) IDENTITY(1,1),
    RANGO_HORARIO_INI DECIMAL(18,2),
    RANGO_HORARIO_FIN DECIMAL(18,2),
	CONSTRAINT PK_DIMENSION_RANGO_HORARIO PRIMARY KEY (RANGO_HORARIO_ID)
);

/*DIMENSION PROVINCIA/LOCALIDAD*/
CREATE TABLE STARSHIP_BI.DIMENSION_LUGAR (
	LUGAR_ID DECIMAL(19,0), --- PK
	LUGAR_LOCALIDAD_NOMBRE NVARCHAR(255),
    LUGAR_PROVINCIA_NOMBRE NVARCHAR(255),
	CONSTRAINT PK_DIMENSION_LUGAR PRIMARY KEY (LUGAR_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_RANGO_ETARIO (
    RANGO_ETARIO_ID DECIMAL(19,0) IDENTITY(1,1), --- PK
    RANGO_ETARIO_INI DECIMAL(19,0),
    RANGO_ETARIO_FIN DECIMAL(19,0),
	CONSTRAINT PK_DIMENSION_RANGO_ETARIO PRIMARY KEY (RANGO_ETARIO_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_TIPO_MEDIO_PAGO (
	MEDIO_PAGO_ID DECIMAL(19, 0) IDENTITY(1,1), --- PK --- DB
	MEDIO_PAGO_TIPO NVARCHAR(255),
    MEDIO_PAGO_MARCA NVARCHAR(255),
	CONSTRAINT PK_DIMENSION_TIPO_MEDIO_PAGO PRIMARY KEY (MEDIO_PAGO_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_NEGOCIO (
    NEGOCIO_ID DECIMAL(19,0), --- PK --- DB
	NEGOCIO_DESCRIPCION NVARCHAR(50),
	CONSTRAINT PK_DIMENSION_NEGOCIO PRIMARY KEY (NEGOCIO_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO (
    CLASIFICACION_NEGOCIO_ID DECIMAL(19,0), --- PK
    CLASIFICACION_NEGOCIO_CATEGORIA NVARCHAR(50),
    CLASIFICACION_NEGOCIO_TIPO NVARCHAR(50),
	CONSTRAINT PK_DIMENSION_CLASIFICACION_NEGOCIO PRIMARY KEY (CLASIFICACION_NEGOCIO_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_TIPO_MOVILIDAD (
    TIPO_MOVILIDAD_ID DECIMAL(19,0), --- PK --- DB
	TIPO_MOVILIDAD_DESCRIPCION NVARCHAR(50),
	CONSTRAINT PK_DIMENSION_TIPO_MOVILIDAD PRIMARY KEY (TIPO_MOVILIDAD_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_TIPO_PAQUETE (
    TIPO_PAQUETE_ID DECIMAL(19,0), --- PK --- DB
	TIPO_PAQUETE_DESCRIPCION NVARCHAR(50),
	CONSTRAINT PK_DIMENSION_TIPO_PAQUETE PRIMARY KEY (TIPO_PAQUETE_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_ESTADO_PEDIDO (
    ESTADO_PEDIDO_ID DECIMAL(19,0), --- PK --- DB
	ESTADO_PEDIDO_DESCRIPCION NVARCHAR(50),
	CONSTRAINT PK_DIMENSION_ESTADO_PEDIDO PRIMARY KEY (ESTADO_PEDIDO_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_ESTADO_ENVIO_MENSAJERIA (
    ESTADO_MENSAJERIA_ID DECIMAL(19,0), --- PK --- DB
	ESTADO_MENSAJERIA_DESCRIPCION NVARCHAR(50),
	CONSTRAINT PK_DIMENSION_ESTADO_ENVIO_MENSAJERIA PRIMARY KEY (ESTADO_MENSAJERIA_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_ESTADO_RECLAMO (
    ESTADO_RECLAMO_ID DECIMAL(19,0), --- PK --- DB
	ESTADO_RECLAMO_DESCRIPCION NVARCHAR(50),
	CONSTRAINT PK_DIMENSION_ESTADO_RECLAMO PRIMARY KEY (ESTADO_RECLAMO_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_TIPO_RECLAMO (
    TIPO_RECLAMO_ID DECIMAL(19,0), --- PK --- DB
	TIPO_RECLAMO_DESCRIPCION NVARCHAR(50),
	CONSTRAINT PK_DIMENSION_TIPO_RECLAMO PRIMARY KEY (TIPO_RECLAMO_ID)
);

CREATE TABLE STARSHIP_BI.DIMENSION_EVENTO (
	EVENTO_ID DECIMAL(19,0) IDENTITY(1,1), --PK
	EVENTO_DESCRIPCIOIN NVARCHAR(100),
	CONSTRAINT PK_DIMENSION_EVENTO PRIMARY KEY (EVENTO_ID)
);

GO

/*/// CREACIÓN DE HECHOS ///////////////////////////////////////// */

CREATE TABLE STARSHIP_BI.HECHOS_PEDIDO (
	DIA_ID DECIMAL(19,0),
	RANGO_HORARIO_ID DECIMAL(19,0),
	LUGAR_ID DECIMAL(19,0),
	CLASIFICACION_NEGOCIO_ID DECIMAL(19,0),
	TIEMPO_ID DECIMAL(19,0),
	ESTADO_PEDIDO_ID DECIMAL(19,0),
	NEGOCIO_ID DECIMAL(19,0),
	RANGO_ETARIO_ID DECIMAL(19,0),
	MEDIO_PAGO_ID DECIMAL(19,0),
	------------------------------------
	CANTIDAD_PEDIDOS DECIMAL(19,0),
	TOTAL_PEDIDOS DECIMAL(18,2),
	CALIFICACION_PEDIDOS DECIMAL(18,0),
	TOTAL_CUPONES DECIMAL(18,2),
	------------------------------------
	CONSTRAINT FK_HP_DIMENSION_DIA FOREIGN KEY (DIA_ID) REFERENCES STARSHIP_BI.DIMENSION_DIA (DIA_ID),
	CONSTRAINT FK_HP_DIMENSION_RANGO_HORARIO FOREIGN KEY (RANGO_HORARIO_ID) REFERENCES STARSHIP_BI.DIMENSION_RANGO_HORARIO (RANGO_HORARIO_ID),
	CONSTRAINT FK_HP_DIMENSION_LUGAR FOREIGN KEY (LUGAR_ID) REFERENCES STARSHIP_BI.DIMENSION_LUGAR (LUGAR_ID),
	CONSTRAINT FK_HP_DIMENSION_CLASIFICACION_NEGOCIO FOREIGN KEY (CLASIFICACION_NEGOCIO_ID) REFERENCES STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO (CLASIFICACION_NEGOCIO_ID),
	CONSTRAINT FK_HP_DIMENSION_TIEMPO FOREIGN KEY (TIEMPO_ID) REFERENCES STARSHIP_BI.DIMENSION_TIEMPO (TIEMPO_ID),
	CONSTRAINT FK_HP_DIMENSION_ESTADO_PEDIDO FOREIGN KEY (ESTADO_PEDIDO_ID) REFERENCES STARSHIP_BI.DIMENSION_ESTADO_PEDIDO (ESTADO_PEDIDO_ID),
	CONSTRAINT FK_HP_DIMENSION_NEGOCIO FOREIGN KEY (NEGOCIO_ID) REFERENCES STARSHIP_BI.DIMENSION_NEGOCIO (NEGOCIO_ID),
	CONSTRAINT FK_HP_DIMENSION_RANGO_ETARIO FOREIGN KEY (RANGO_ETARIO_ID) REFERENCES STARSHIP_BI.DIMENSION_RANGO_ETARIO (RANGO_ETARIO_ID),
	CONSTRAINT FK_HP_DIMENSION_TIPO_MEDIO_PAGO FOREIGN KEY (MEDIO_PAGO_ID) REFERENCES STARSHIP_BI.DIMENSION_TIPO_MEDIO_PAGO (MEDIO_PAGO_ID),
	CONSTRAINT PK_HECHOS_PEDIDO_HP PRIMARY KEY (DIA_ID,RANGO_HORARIO_ID,LUGAR_ID,CLASIFICACION_NEGOCIO_ID,TIEMPO_ID,ESTADO_PEDIDO_ID,NEGOCIO_ID,RANGO_ETARIO_ID,MEDIO_PAGO_ID)
);


CREATE TABLE STARSHIP_BI.HECHOS_ENVIO (
	EVENTO_ID DECIMAL(19,0),
	TIEMPO_ID DECIMAL(19,0),
	LUGAR_ID DECIMAL(19,0),
	-------------------------------
	TIPO_MOVILIDAD_ID DECIMAL(19,0),
	DIA_ID DECIMAL(19,0),
	RANGO_HORARIO_ID DECIMAL(19,0),
	-------------------------------
	RANGO_ETARIO_ID DECIMAL(19,0),
	ESTADO_PEDIDO_ID DECIMAL(19,0),
	ESTADO_MENSAJERIA_ID DECIMAL(19,0),
	-------------------------------
	TIPO_PAQUETE_ID DECIMAL(19,0),
	--------------------------------------------------
	TOTAL_ENVIO DECIMAL(18,2),
	CANTIDAD_EVENTOS DECIMAL(18,2),
	DESVIO DECIMAL(18,2),
	TOTAL_VALOR_ASEGURADO DECIMAL(18,2),
	--------------------------------------------------
	CONSTRAINT FK_HE_DIMENSION_EVENTO FOREIGN KEY (EVENTO_ID) REFERENCES STARSHIP_BI.DIMENSION_EVENTO (EVENTO_ID),
	CONSTRAINT FK_HE_DIMENSION_TIEMPO FOREIGN KEY (TIEMPO_ID) REFERENCES STARSHIP_BI.DIMENSION_TIEMPO (TIEMPO_ID),
	CONSTRAINT FK_HE_DIMENSION_LUGAR FOREIGN KEY (LUGAR_ID) REFERENCES STARSHIP_BI.DIMENSION_LUGAR (LUGAR_ID),
	CONSTRAINT FK_HE_DIMENSION_TIPO_MOVILIDAD FOREIGN KEY (TIPO_MOVILIDAD_ID) REFERENCES STARSHIP_BI.DIMENSION_TIPO_MOVILIDAD (TIPO_MOVILIDAD_ID),
	CONSTRAINT FK_HE_DIMENSION_DIA FOREIGN KEY (DIA_ID) REFERENCES STARSHIP_BI.DIMENSION_DIA (DIA_ID),
	CONSTRAINT FK_HE_DIMENSION_RANGO_HORARIO FOREIGN KEY (RANGO_HORARIO_ID) REFERENCES STARSHIP_BI.DIMENSION_RANGO_HORARIO (RANGO_HORARIO_ID),
	CONSTRAINT FK_HE_DIMENSION_RANGO_ETARIO FOREIGN KEY (RANGO_ETARIO_ID) REFERENCES STARSHIP_BI.DIMENSION_RANGO_ETARIO (RANGO_ETARIO_ID),
	CONSTRAINT FK_HE_DIMENSION_ESTADO_PEDIDO FOREIGN KEY (ESTADO_PEDIDO_ID) REFERENCES STARSHIP_BI.DIMENSION_ESTADO_PEDIDO (ESTADO_PEDIDO_ID),
	CONSTRAINT FK_HE_DIMENSION_ESTADO_MENSAJERIA FOREIGN KEY (ESTADO_MENSAJERIA_ID) REFERENCES STARSHIP_BI.DIMENSION_ESTADO_ENVIO_MENSAJERIA (ESTADO_MENSAJERIA_ID),
	CONSTRAINT FK_HE_DIMENSION_TIPO_PAQUETE FOREIGN KEY (TIPO_PAQUETE_ID) REFERENCES STARSHIP_BI.DIMENSION_TIPO_PAQUETE (TIPO_PAQUETE_ID),
	CONSTRAINT PK_HECHOS_ENVIO_MENS_HE PRIMARY KEY (EVENTO_ID,TIEMPO_ID,LUGAR_ID,TIPO_MOVILIDAD_ID,DIA_ID,RANGO_HORARIO_ID,RANGO_ETARIO_ID,ESTADO_PEDIDO_ID,ESTADO_MENSAJERIA_ID,TIPO_PAQUETE_ID)
);


CREATE TABLE STARSHIP_BI.HECHOS_RECLAMO (
	TIEMPO_ID DECIMAL(19,0),
	NEGOCIO_ID DECIMAL(19,0),
	DIA_ID DECIMAL(19,0),
	RANGO_HORARIO_ID DECIMAL(19,0),
	TIPO_RECLAMO_ID DECIMAL(19,0),
	ESTADO_RECLAMO_ID DECIMAL(19,0),
	RANGO_ETARIO_ID DECIMAL(19,0),
	-------------------------------------------
	CANTIDAD_RECLAMOS DECIMAL(18,2),
	TIEMPO_RESOLUCION DECIMAL(18,2),
	MONTO_EN_CUPONES DECIMAL(18,2),
	-------------------------------------------
	CONSTRAINT FK_HR_DIMENSION_TIEMPO FOREIGN KEY (TIEMPO_ID) REFERENCES STARSHIP_BI.DIMENSION_TIEMPO (TIEMPO_ID),
	CONSTRAINT FK_HR_DIMENSION_NEGOCIO FOREIGN KEY (NEGOCIO_ID) REFERENCES STARSHIP_BI.DIMENSION_NEGOCIO (NEGOCIO_ID),
	CONSTRAINT FK_HR_DIMENSION_DIA FOREIGN KEY (DIA_ID) REFERENCES STARSHIP_BI.DIMENSION_DIA (DIA_ID),
	CONSTRAINT FK_HR_DIMENSION_RANGO_HORARIO FOREIGN KEY (RANGO_HORARIO_ID) REFERENCES STARSHIP_BI.DIMENSION_RANGO_HORARIO (RANGO_HORARIO_ID),
	CONSTRAINT FK_HR_DIMENSION_TIPO_RECLAMO FOREIGN KEY (TIPO_RECLAMO_ID) REFERENCES STARSHIP_BI.DIMENSION_TIPO_RECLAMO (TIPO_RECLAMO_ID),
	CONSTRAINT FK_HR_DIMENSION_ESTADO_RECLAMO FOREIGN KEY (ESTADO_RECLAMO_ID) REFERENCES STARSHIP_BI.DIMENSION_ESTADO_RECLAMO (ESTADO_RECLAMO_ID),
	CONSTRAINT FK_HR_DIMENSION_RANGO_ETARIO FOREIGN KEY (RANGO_ETARIO_ID) REFERENCES STARSHIP_BI.DIMENSION_RANGO_ETARIO (RANGO_ETARIO_ID),
	CONSTRAINT PK_HECHOS_RECLAMO_HR PRIMARY KEY (TIEMPO_ID,NEGOCIO_ID,DIA_ID,RANGO_HORARIO_ID,TIPO_RECLAMO_ID,ESTADO_RECLAMO_ID,RANGO_ETARIO_ID)
);


GO
/*/// CREACIÓN DE PROCEDURES ///////////////////////////////////////// */
CREATE PROCEDURE STARSHIP_BI.migrar_dimension_dia
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_DIA (
        DIA_ID,
        DIA_DETALLE
    )
	SELECT 
        dia_codigo,
        dia_detalle
    FROM STARSHIP.dia
END
GO --select * from STARSHIP_BI.DIMENSION_DIA


CREATE PROCEDURE STARSHIP_BI.migrar_dimension_tiempo
AS
BEGIN
	INSERT INTO STARSHIP_BI.dimension_tiempo (
        TIEMPO_MES,
        TIEMPO_ANIO
    )

    (
	SELECT
		MONTH(mens_fecha_hora_pedi),
        YEAR(mens_fecha_hora_pedi)
	FROM STARSHIP.Envio_Mensajeria
	GROUP BY MONTH(mens_fecha_hora_pedi), YEAR(mens_fecha_hora_pedi)
	
    UNION
	
    SELECT
		MONTH(mens_fecha_hora_entr),
        YEAR(mens_fecha_hora_entr)
	FROM STARSHIP.Envio_Mensajeria
	GROUP BY MONTH(mens_fecha_hora_entr), YEAR(mens_fecha_hora_entr)
	
    UNION

	SELECT
		MONTH(recl_fecha),
        YEAR(recl_fecha)
	FROM STARSHIP.Reclamo
	GROUP BY MONTH(recl_fecha), YEAR(recl_fecha)

	UNION

	SELECT
		MONTH(recl_fecha_sol),
        YEAR(recl_fecha_sol)
	FROM STARSHIP.Reclamo
	GROUP BY MONTH(recl_fecha_sol), YEAR(recl_fecha_sol)
	
    UNION

	SELECT
		MONTH(clie_fecha_registro),
        YEAR(clie_fecha_registro)
	FROM STARSHIP.Cliente
	GROUP BY MONTH(clie_fecha_registro), YEAR(clie_fecha_registro)
	
    UNION

	SELECT
		MONTH(cupon_fecha_alta),
        YEAR(cupon_fecha_alta)
	FROM STARSHIP.Cupon_Descuento
	GROUP BY MONTH(cupon_fecha_alta), YEAR(cupon_fecha_alta)

	UNION

	SELECT
		MONTH(cupon_fecha_venc),
        YEAR(cupon_fecha_venc)
	FROM STARSHIP.Cupon_Descuento
	GROUP BY MONTH(cupon_fecha_venc), YEAR(cupon_fecha_venc)

	UNION

	SELECT
		MONTH(pedi_fecha_hora_pedi),
        YEAR(pedi_fecha_hora_pedi)
	FROM STARSHIP.Pedido
	GROUP BY MONTH(pedi_fecha_hora_pedi), YEAR(pedi_fecha_hora_pedi)
	
    UNION

	SELECT
		MONTH(pedi_fecha_hora_entr),
        YEAR(pedi_fecha_hora_entr)
	FROM STARSHIP.Pedido
	GROUP BY MONTH(pedi_fecha_hora_entr),YEAR(pedi_fecha_hora_entr)
    )
    ORDER BY 2, 1
END
GO --select * from STARSHIP_BI.DIMENSION_TIEMPO


CREATE PROCEDURE STARSHIP_BI.insertar_dimension_rango_horario
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_RANGO_HORARIO (
        RANGO_HORARIO_INI,
        RANGO_HORARIO_FIN
    )
	VALUES 
        (8, 10),
        (10, 12),
        (12, 14),
        (14, 16),
        (16, 18),
        (18, 20),
        (20, 22),
        (22, 24)
END
GO --select * from STARSHIP_BI.DIMENSION_RANGO_HORARIO


/*DIMENSION PROVINCIA/LOCALIDAD*/
CREATE PROCEDURE STARSHIP_BI.migrar_dimension_lugar
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_LUGAR (
		LUGAR_ID,
        LUGAR_LOCALIDAD_NOMBRE,
        LUGAR_PROVINCIA_NOMBRE
    )

	SELECT
		locali_codigo,
        locali_nombre,
        prov_nombre
    FROM STARSHIP.Localidad 
	JOIN STARSHIP.Provincia ON prov_codigo = locali_prov
END
GO --select * from STARSHIP_BI.DIMENSION_LUGAR


CREATE PROCEDURE STARSHIP_BI.insertar_rango_hetario
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_RANGO_ETARIO (
        RANGO_ETARIO_INI,
        RANGO_ETARIO_FIN
    )
    VALUES
        (0, 24),
        (25, 35),
        (36, 55),
        (56, 999)
END
GO --select * from STARSHIP_BI.DIMENSION_RANGO_ETARIO


CREATE PROCEDURE STARSHIP_BI.migrar_dimension_tipo_medio_pago
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_TIPO_MEDIO_PAGO (
        MEDIO_PAGO_TIPO,
        MEDIO_PAGO_MARCA
    )
	SELECT
        tipo_medio_detalle,
        marca_tarjeta_detalle
    FROM STARSHIP.Medio_Pago
    JOIN STARSHIP.Tipo_Medio_Pago on tipo_medio_id = medi_tipo
    JOIN STARSHIP.Tarjeta on tarj_codigo = medi_tarjeta
    JOIN STARSHIP.Marca_Tarjeta on marca_tarjeta_cod = tarj_marca
    GROUP BY tipo_medio_detalle, marca_tarjeta_detalle
END
GO --select * from STARSHIP_BI.DIMENSION_TIPO_MEDIO_PAGO


CREATE PROCEDURE STARSHIP_BI.migrar_dimension_negocio
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_NEGOCIO (
        NEGOCIO_ID,
        NEGOCIO_DESCRIPCION
    )
	SELECT
        nego_codigo,
        nego_nombre
    FROM STARSHIP.Negocio
END
GO --select * from STARSHIP_BI.DIMENSION_NEGOCIO


/* TIPO NEGOCIO / CATEGORIA */
CREATE PROCEDURE STARSHIP_BI.migrar_dimension_clasificacion_negocio
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO (
        CLASIFICACION_NEGOCIO_ID,
        CLASIFICACION_NEGOCIO_CATEGORIA,
	    CLASIFICACION_NEGOCIO_TIPO
    )
	SELECT
        categ_nego_id,
        categ_nego_detalle,
        tipo_nego_detalle
    FROM STARSHIP.Categoria_Negocio
    JOIN STARSHIP.Tipo_Negocio ON categ_nego_tipo = tipo_nego_id
END
GO --select * from STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO


CREATE PROCEDURE STARSHIP_BI.migrar_dimension_tipo_movilidad
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_TIPO_MOVILIDAD (
        TIPO_MOVILIDAD_ID,
	    TIPO_MOVILIDAD_DESCRIPCION
    )
	SELECT
        tipo_movi_codigo,
        tipo_movi_detalle
    FROM STARSHIP.Tipo_Movilidad
END
GO --select * from STARSHIP_BI.DIMENSION_TIPO_MOVILIDAD


CREATE PROCEDURE STARSHIP_BI.migrar_dimension_tipo_paquete
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_TIPO_PAQUETE (
        TIPO_PAQUETE_ID,
	    TIPO_PAQUETE_DESCRIPCION
    )
	SELECT
        tipo_paqu_codigo,
        tipo_paqu_detalle
    FROM STARSHIP.Tipo_Paquete

	INSERT INTO STARSHIP_BI.DIMENSION_TIPO_PAQUETE (
        TIPO_PAQUETE_ID,
	    TIPO_PAQUETE_DESCRIPCION
    )
	VALUES (0, 'NONE')
END
GO --select * from STARSHIP_BI.DIMENSION_TIPO_PAQUETE


CREATE PROCEDURE STARSHIP_BI.migrar_dimension_estado_pedido
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_ESTADO_PEDIDO (
        ESTADO_PEDIDO_ID,
	    ESTADO_PEDIDO_DESCRIPCION
    )
	SELECT
        pedi_estado_codigo,
        pedi_estado_detalle
    FROM STARSHIP.Pedido_Estado

	INSERT INTO STARSHIP_BI.DIMENSION_ESTADO_PEDIDO (
        ESTADO_PEDIDO_ID,
	    ESTADO_PEDIDO_DESCRIPCION
    )
	VALUES (0, 'NONE')
END
GO --select * from STARSHIP_BI.DIMENSION_ESTADO_PEDIDO


CREATE PROCEDURE STARSHIP_BI.migrar_dimension_estado_envio_mensajeria
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_ESTADO_ENVIO_MENSAJERIA (
        ESTADO_MENSAJERIA_ID,
	    ESTADO_MENSAJERIA_DESCRIPCION
    )
	SELECT
        mens_esta_codigo,
        mens_esta_detalle
    FROM STARSHIP.Mens_Estado

	INSERT INTO STARSHIP_BI.DIMENSION_ESTADO_ENVIO_MENSAJERIA (
        ESTADO_MENSAJERIA_ID,
	    ESTADO_MENSAJERIA_DESCRIPCION
    )
	VALUES (0, 'NONE')
END
GO --select * from STARSHIP_BI.DIMENSION_ESTADO_ENVIO_MENSAJERIA


CREATE PROCEDURE STARSHIP_BI.migrar_dimension_estado_reclamo
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_ESTADO_RECLAMO (
        ESTADO_RECLAMO_ID,
	    ESTADO_RECLAMO_DESCRIPCION
    )
	SELECT
        recl_estado_id,
        recl_estado_detalle
    FROM STARSHIP.Recl_Estado
END
GO --select * from STARSHIP_BI.DIMENSION_ESTADO_RECLAMO


--STARSHIP_BI.DIMENSION_TIPO_RECLAMO
CREATE PROCEDURE STARSHIP_BI.migrar_dimension_tipo_reclamo
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_TIPO_RECLAMO (
        TIPO_RECLAMO_ID,
	    TIPO_RECLAMO_DESCRIPCION
    )
	SELECT
        tipo_rec_id,
        tipo_rec_detalle
    FROM STARSHIP.Tipo_Reclamo
END
GO --select * from STARSHIP_BI.DIMENSION_TIPO_RECLAMO


CREATE PROCEDURE STARSHIP_BI.insertar_dimension_evento
AS
BEGIN
	INSERT INTO STARSHIP_BI.DIMENSION_EVENTO (
		EVENTO_DESCRIPCIOIN
	)
	VALUES
		('PEDIDO'),
		('ENVIO_MENSAJERIA')
END
GO --select * from STARSHIP_BI.DIMENSION_EVENTO


----------------------------------------------------------------------------------------

--STARSHIP_BI.HECHOS_PEDIDO
CREATE PROCEDURE STARSHIP_BI.migrar_hechos_pedido
AS
BEGIN
	INSERT INTO STARSHIP_BI.HECHOS_PEDIDO (
		DIA_ID,
		RANGO_HORARIO_ID,
		LUGAR_ID,
		CLASIFICACION_NEGOCIO_ID,
		TIEMPO_ID,

		ESTADO_PEDIDO_ID,
		NEGOCIO_ID,

		RANGO_ETARIO_ID,
		MEDIO_PAGO_ID,
		-----------------------------
		CANTIDAD_PEDIDOS,
		TOTAL_PEDIDOS,
		CALIFICACION_PEDIDOS,
		TOTAL_CUPONES
	)
	SELECT
		DIA_ID,
		RANGO_HORARIO_ID,
		LUGAR_ID,
		CLASIFICACION_NEGOCIO_ID,
		TIEMPO_ID,
		ESTADO_PEDIDO_ID,
		NEGOCIO_ID,
		DIM_RE.RANGO_ETARIO_ID,
		MEDIO_PAGO_ID,
		COUNT(P.pedi_numero),
		SUM(P.pedi_total_productos),
		SUM(P.pedi_calificacion),
		SUM(P.pedi_total_cupones)
	FROM STARSHIP.Pedido P
	JOIN STARSHIP_BI.DIMENSION_DIA ON DIA_ID = DATEPART(WEEKDAY, P.pedi_fecha_hora_pedi)
	JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO ON  
	(DATEPART(HOUR, P.pedi_fecha_hora_pedi)+0.01*DATEPART(MINUTE, P.pedi_fecha_hora_pedi)) >= RANGO_HORARIO_INI
	AND (DATEPART(HOUR, P.pedi_fecha_hora_pedi)+0.01*DATEPART(MINUTE, P.pedi_fecha_hora_pedi)) < RANGO_HORARIO_FIN
	AND (DATEPART(HOUR, P.pedi_fecha_hora_pedi)+0.01*DATEPART(MINUTE, P.pedi_fecha_hora_pedi)) BETWEEN RANGO_HORARIO_INI AND RANGO_HORARIO_FIN
	JOIN STARSHIP.Envio ON envi_numero = P.pedi_envio
	JOIN STARSHIP.Direccion ON dir_codigo = envi_dir_codigo
	JOIN STARSHIP.Localidad ON locali_codigo = dir_local_codigo
	JOIN STARSHIP.Provincia ON prov_codigo = locali_prov
	JOIN STARSHIP_BI.DIMENSION_LUGAR ON LUGAR_LOCALIDAD_NOMBRE = locali_nombre AND LUGAR_PROVINCIA_NOMBRE = prov_nombre
	JOIN STARSHIP.Negocio ON nego_codigo = P.pedi_nego_codigo
	JOIN STARSHIP.Categoria_Negocio ON categ_nego_id = nego_categ
	JOIN STARSHIP.Tipo_Negocio ON tipo_nego_id = categ_nego_tipo
	JOIN STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO ON CLASIFICACION_NEGOCIO_CATEGORIA = categ_nego_detalle AND CLASIFICACION_NEGOCIO_TIPO = tipo_nego_detalle
	JOIN STARSHIP_BI.DIMENSION_TIEMPO ON TIEMPO_ANIO = YEAR(P.pedi_fecha_hora_pedi) AND TIEMPO_MES = MONTH(P.pedi_fecha_hora_pedi)
	JOIN STARSHIP_BI.DIMENSION_ESTADO_PEDIDO ON ESTADO_PEDIDO_ID = P.pedi_estado
	JOIN STARSHIP_BI.DIMENSION_NEGOCIO ON NEGOCIO_ID = nego_codigo
	JOIN STARSHIP.Cliente ON clie_codigo = P.pedi_usuario
	JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO DIM_RE ON DATEDIFF(YEAR,clie_nacimiento,GETDATE()) BETWEEN RANGO_ETARIO_INI AND RANGO_ETARIO_FIN
	JOIN STARSHIP.Medio_Pago ON medi_codigo = P.pedi_medio_pago
	JOIN STARSHIP.Tipo_Medio_Pago on tipo_medio_id = medi_tipo
    JOIN STARSHIP.Tarjeta on tarj_codigo = medi_tarjeta
    JOIN STARSHIP.Marca_Tarjeta on marca_tarjeta_cod = tarj_marca
	JOIN STARSHIP_BI.DIMENSION_TIPO_MEDIO_PAGO ON MEDIO_PAGO_MARCA = marca_tarjeta_detalle AND MEDIO_PAGO_TIPO = tipo_medio_detalle
	GROUP BY 
		DIA_ID,
		RANGO_HORARIO_ID,
		LUGAR_ID,
		CLASIFICACION_NEGOCIO_ID,
		TIEMPO_ID,
		ESTADO_PEDIDO_ID,
		NEGOCIO_ID,
		DIM_RE.RANGO_ETARIO_ID,
		MEDIO_PAGO_ID
END
GO --select * from STARSHIP_BI.HECHOS_PEDIDO --49740


CREATE PROCEDURE STARSHIP_BI.migrar_hechos_envio
AS
BEGIN
	INSERT INTO STARSHIP_BI.HECHOS_ENVIO (
		EVENTO_ID,

		TIEMPO_ID,
		LUGAR_ID,

		TIPO_MOVILIDAD_ID,
		DIA_ID,
		RANGO_HORARIO_ID,

		RANGO_ETARIO_ID,
		ESTADO_PEDIDO_ID,
		ESTADO_MENSAJERIA_ID,

		TIPO_PAQUETE_ID,
		-------------------------
		TOTAL_ENVIO,
		CANTIDAD_EVENTOS,
		DESVIO,
		TOTAL_VALOR_ASEGURADO
	)
	SELECT
		(SELECT DIM_EVE.EVENTO_ID FROM STARSHIP_BI.DIMENSION_EVENTO DIM_EVE WHERE DIM_EVE.EVENTO_DESCRIPCIOIN = 'ENVIO_MENSAJERIA'),
		TIEMPO_ID,
		LUGAR_ID,
		TIPO_MOVILIDAD_ID,
		DIA_ID,
		RANGO_HORARIO_ID,
		RANGO_ETARIO_ID,
		(SELECT ESTADO_PEDIDO_ID FROM STARSHIP_BI.DIMENSION_ESTADO_PEDIDO WHERE ESTADO_PEDIDO_DESCRIPCION = 'NONE'),
		ESTADO_MENSAJERIA_ID,
		TIPO_PAQUETE_ID,
		--------------------------------------
		SUM(mens_precio_envio),
		COUNT(ENVI_MENS.mens_numero),
		SUM(ENVI_MENS.mens_tiempo_estimado - DATEDIFF(MINUTE, mens_fecha_hora_pedi, mens_fecha_hora_entr)),
		SUM(mens_valor_asegurado)
	FROM STARSHIP.Envio_Mensajeria ENVI_MENS
	JOIN STARSHIP.Paquete ON paqu_mens_numero = ENVI_MENS.mens_numero
	JOIN STARSHIP_BI.DIMENSION_TIEMPO ON TIEMPO_ANIO = YEAR(ENVI_MENS.mens_fecha_hora_pedi) AND TIEMPO_MES = MONTH(ENVI_MENS.mens_fecha_hora_pedi)
	JOIN STARSHIP.Localidad ON locali_codigo = ENVI_MENS.mens_localidad
	JOIN STARSHIP.Provincia ON prov_codigo = locali_prov
	JOIN STARSHIP_BI.DIMENSION_LUGAR ON LUGAR_LOCALIDAD_NOMBRE = locali_nombre AND LUGAR_PROVINCIA_NOMBRE = prov_nombre
	JOIN STARSHIP.Repartidor ON repa_codigo = ENVI_MENS.mens_repa_codigo
	JOIN STARSHIP.Tipo_Movilidad ON tipo_movi_codigo = repa_tipo_mov
	JOIN STARSHIP_BI.DIMENSION_TIPO_MOVILIDAD ON TIPO_MOVILIDAD_DESCRIPCION = tipo_movi_detalle
	JOIN STARSHIP_BI.DIMENSION_DIA ON DIA_ID = DATEPART(WEEKDAY, mens_fecha_hora_pedi)
	JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO ON 
	(DATEPART(HOUR, mens_fecha_hora_pedi)+0.01*DATEPART(MINUTE, mens_fecha_hora_pedi)) >= RANGO_HORARIO_INI
	AND (DATEPART(HOUR, mens_fecha_hora_pedi)+0.01*DATEPART(MINUTE, mens_fecha_hora_pedi)) < RANGO_HORARIO_FIN
	AND (DATEPART(HOUR, mens_fecha_hora_pedi)+0.01*DATEPART(MINUTE, mens_fecha_hora_pedi)) BETWEEN RANGO_HORARIO_INI AND RANGO_HORARIO_FIN
	JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO ON DATEDIFF(YEAR, repa_nacimiento, GETDATE()) BETWEEN RANGO_ETARIO_INI AND RANGO_ETARIO_FIN
	JOIN STARSHIP.Mens_Estado ME ON ME.mens_esta_codigo = ENVI_MENS.mens_estado_codigo
	JOIN STARSHIP_BI.DIMENSION_ESTADO_ENVIO_MENSAJERIA ON ESTADO_MENSAJERIA_DESCRIPCION = ME.mens_esta_detalle
	JOIN STARSHIP.Tipo_Paquete ON tipo_paqu_codigo = paqu_tipo
	JOIN STARSHIP_BI.DIMENSION_TIPO_PAQUETE ON TIPO_PAQUETE_DESCRIPCION = tipo_paqu_detalle
	GROUP BY
		TIEMPO_ID,
		LUGAR_ID,
		TIPO_MOVILIDAD_ID,
		DIA_ID,
		RANGO_HORARIO_ID,
		RANGO_ETARIO_ID,
		ESTADO_MENSAJERIA_ID,
		TIPO_PAQUETE_ID
	
	/*=========================================================*/
	INSERT INTO STARSHIP_BI.HECHOS_ENVIO (
		EVENTO_ID,

		TIEMPO_ID,
		LUGAR_ID,

		TIPO_MOVILIDAD_ID,
		DIA_ID,
		RANGO_HORARIO_ID,

		RANGO_ETARIO_ID,
		ESTADO_PEDIDO_ID,
		ESTADO_MENSAJERIA_ID,

		TIPO_PAQUETE_ID,
		-------------------------
		TOTAL_ENVIO,
		CANTIDAD_EVENTOS,
		DESVIO,
		TOTAL_VALOR_ASEGURADO
	)
	(SELECT
		(SELECT DIM_EVE.EVENTO_ID FROM STARSHIP_BI.DIMENSION_EVENTO DIM_EVE WHERE DIM_EVE.EVENTO_DESCRIPCIOIN = 'PEDIDO'),
		TIEMPO_ID,
		LUGAR_ID,
		TIPO_MOVILIDAD_ID,
		DIA_ID,
		RANGO_HORARIO_ID,
		RANGO_ETARIO_ID,
		ESTADO_PEDIDO_ID,
		(SELECT ESTADO_MENSAJERIA_ID FROM STARSHIP_BI.DIMENSION_ESTADO_ENVIO_MENSAJERIA WHERE ESTADO_MENSAJERIA_DESCRIPCION = 'NONE'),
		(SELECT TIPO_PAQUETE_ID FROM STARSHIP_BI.DIMENSION_TIPO_PAQUETE WHERE TIPO_PAQUETE_DESCRIPCION = 'NONE'),
		--------------------------------
		SUM(envi_precio),
		COUNT(envi_numero),
		SUM((pedi_tiempo_estimado)-(DATEDIFF(MINUTE, pedi_fecha_hora_pedi, pedi_fecha_hora_entr))),
		SUM(0)
	FROM STARSHIP.Envio ENVI_PED
	JOIN STARSHIP.Pedido ON pedi_envio = ENVI_PED.envi_numero
	JOIN STARSHIP_BI.DIMENSION_TIEMPO ON TIEMPO_ANIO = YEAR(pedi_fecha_hora_pedi) AND TIEMPO_MES = MONTH(pedi_fecha_hora_pedi)
	JOIN STARSHIP.Direccion ON dir_codigo = ENVI_PED.envi_dir_codigo
	JOIN STARSHIP.Localidad ON locali_codigo = dir_local_codigo
	JOIN STARSHIP.Provincia ON prov_codigo = locali_prov
	JOIN STARSHIP_BI.DIMENSION_LUGAR ON LUGAR_LOCALIDAD_NOMBRE = locali_nombre AND LUGAR_PROVINCIA_NOMBRE = prov_nombre
	JOIN STARSHIP.Repartidor ON repa_codigo = ENVI_PED.envi_repartidor
	JOIN STARSHIP.Tipo_Movilidad ON tipo_movi_codigo = repa_tipo_mov
	JOIN STARSHIP_BI.DIMENSION_TIPO_MOVILIDAD ON TIPO_MOVILIDAD_DESCRIPCION = tipo_movi_detalle
	JOIN STARSHIP_BI.DIMENSION_DIA ON DIA_ID = DATEPART(WEEKDAY, pedi_fecha_hora_pedi)
	JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO ON 
	(DATEPART(HOUR, pedi_fecha_hora_pedi)+0.01*DATEPART(MINUTE, pedi_fecha_hora_pedi)) >= RANGO_HORARIO_INI
	AND (DATEPART(HOUR, pedi_fecha_hora_pedi)+0.01*DATEPART(MINUTE, pedi_fecha_hora_pedi)) < RANGO_HORARIO_FIN
	AND (DATEPART(HOUR, pedi_fecha_hora_pedi)+0.01*DATEPART(MINUTE, pedi_fecha_hora_pedi)) BETWEEN RANGO_HORARIO_INI AND RANGO_HORARIO_FIN
	JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO ON DATEDIFF(YEAR, repa_nacimiento, GETDATE()) BETWEEN RANGO_ETARIO_INI AND RANGO_ETARIO_FIN
	JOIN STARSHIP.Pedido_Estado ON pedi_estado_codigo = pedi_estado
	JOIN STARSHIP_BI.DIMENSION_ESTADO_PEDIDO ON ESTADO_PEDIDO_DESCRIPCION = pedi_estado_detalle
	GROUP BY
		TIEMPO_ID,
		LUGAR_ID,
		TIPO_MOVILIDAD_ID,
		DIA_ID,
		RANGO_HORARIO_ID,
		RANGO_ETARIO_ID,
		ESTADO_PEDIDO_ID
	)
END
GO --select * from STARSHIP_BI.HECHOS_ENVIO --95619


CREATE PROCEDURE STARSHIP_BI.migrar_hechos_reclamo
AS
BEGIN
	INSERT INTO STARSHIP_BI.HECHOS_RECLAMO (
		TIEMPO_ID,
		NEGOCIO_ID,
		DIA_ID,
		RANGO_HORARIO_ID,
		TIPO_RECLAMO_ID,
		ESTADO_RECLAMO_ID,
		RANGO_ETARIO_ID,
		-----------------------------------
		CANTIDAD_RECLAMOS,
		TIEMPO_RESOLUCION,
		MONTO_EN_CUPONES
	)
	SELECT
		TIEMPO_ID,
		NEGOCIO_ID,
		DIA_ID,
		RANGO_HORARIO_ID,
		TIPO_RECLAMO_ID,
		ESTADO_RECLAMO_ID,
		RANGO_ETARIO_ID,
		------------------------------------
		COUNT(R.recl_numero),
		SUM(DATEDIFF(MINUTE,recl_fecha,recl_fecha_sol)),
		SUM(cupon_valor)
	FROM STARSHIP.Reclamo R
	JOIN STARSHIP_BI.DIMENSION_TIEMPO ON TIEMPO_ANIO = YEAR(R.recl_fecha) AND TIEMPO_MES = MONTH(R.recl_fecha)
	JOIN STARSHIP.Pedido ON pedi_numero = R.recl_pedido
	JOIN STARSHIP.Negocio ON nego_codigo = pedi_nego_codigo
	JOIN STARSHIP_BI.DIMENSION_NEGOCIO ON NEGOCIO_ID = nego_codigo
	JOIN STARSHIP_BI.DIMENSION_DIA ON DIA_ID = DATEPART(WEEKDAY, R.recl_fecha)
	JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO ON 
	(DATEPART(HOUR, R.recl_fecha)+0.01*DATEPART(MINUTE, R.recl_fecha)) >= RANGO_HORARIO_INI
	AND (DATEPART(HOUR, R.recl_fecha)+0.01*DATEPART(MINUTE, R.recl_fecha)) < RANGO_HORARIO_FIN
	AND (DATEPART(HOUR, R.recl_fecha)+0.01*DATEPART(MINUTE, R.recl_fecha)) BETWEEN RANGO_HORARIO_INI AND RANGO_HORARIO_FIN
	JOIN STARSHIP.Tipo_Reclamo ON tipo_rec_id = R.recl_tipo
	JOIN STARSHIP_BI.DIMENSION_TIPO_RECLAMO ON TIPO_RECLAMO_DESCRIPCION = tipo_rec_detalle
	JOIN STARSHIP.Operador ON oper_codigo = R.recl_operador
	JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO ON DATEDIFF(YEAR,oper_nacimiento,GETDATE()) BETWEEN RANGO_ETARIO_INI AND RANGO_ETARIO_FIN
	JOIN STARSHIP.Recl_Estado ON recl_estado_id = R.recl_estado
	JOIN STARSHIP_BI.DIMENSION_ESTADO_RECLAMO ON ESTADO_RECLAMO_ID = recl_estado_id

	JOIN STARSHIP.Cupon_Reclamo ON cupon_recl_recl = R.recl_numero
	JOIN STARSHIP.Cupon_Descuento ON cupon_id = cupon_recl_cupon
	GROUP BY
		TIEMPO_ID,
		NEGOCIO_ID,
		DIA_ID,
		RANGO_HORARIO_ID,
		TIPO_RECLAMO_ID,
		ESTADO_RECLAMO_ID,
		RANGO_ETARIO_ID
END
GO --select * from STARSHIP_BI.HECHOS_RECLAMO --11078


/*/// EXECUTE PROCEDURES ///////////////////////////////////////// */
EXECUTE STARSHIP_BI.migrar_dimension_tiempo
EXECUTE STARSHIP_BI.migrar_dimension_dia
EXECUTE STARSHIP_BI.insertar_dimension_rango_horario
EXECUTE STARSHIP_BI.migrar_dimension_lugar
EXECUTE STARSHIP_BI.insertar_rango_hetario
EXECUTE STARSHIP_BI.migrar_dimension_tipo_medio_pago
EXECUTE STARSHIP_BI.migrar_dimension_negocio
EXECUTE STARSHIP_BI.migrar_dimension_clasificacion_negocio
EXECUTE STARSHIP_BI.migrar_dimension_tipo_movilidad
EXECUTE STARSHIP_BI.migrar_dimension_tipo_paquete
EXECUTE STARSHIP_BI.migrar_dimension_estado_pedido
EXECUTE STARSHIP_BI.migrar_dimension_estado_envio_mensajeria
EXECUTE STARSHIP_BI.migrar_dimension_estado_reclamo
EXECUTE STARSHIP_BI.migrar_dimension_tipo_reclamo
EXECUTE STARSHIP_BI.insertar_dimension_evento

-------------------------------------

EXECUTE STARSHIP_BI.migrar_hechos_pedido
EXECUTE STARSHIP_BI.migrar_hechos_envio
EXECUTE STARSHIP_BI.migrar_hechos_reclamo

GO
/*/// CREACIÓN DE VIEW ///////////////////////////////////////// */

/* /////////////////////////////////////////////////////////////////////////
Día de la semana y franja horaria con mayor cantidad de pedidos según la
localidad y categoría del local, para cada mes de cada año.
*/
CREATE VIEW STARSHIP_BI.VIEW_01_MAYOR_CANTIDAD_DE_PEDIDOS
AS
	SELECT
		DIM_T.TIEMPO_ANIO AS 'ANIO',
		DIM_T.TIEMPO_MES AS 'MES',
		DIM_LU.LUGAR_ID,
		DIM_LU.LUGAR_PROVINCIA_NOMBRE AS 'PROVINCIA',
		DIM_LU.LUGAR_LOCALIDAD_NOMBRE AS 'LOCALIDAD',
		DIM_CN.CLASIFICACION_NEGOCIO_ID,
		CASE
		WHEN DIM_CN.CLASIFICACION_NEGOCIO_ID IN (SELECT CLASIFICACION_NEGOCIO_ID FROM STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO)
		THEN
			(SELECT X1.CLASIFICACION_NEGOCIO_TIPO + ' ' + X1.CLASIFICACION_NEGOCIO_CATEGORIA
			FROM STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO X1 
			WHERE X1.CLASIFICACION_NEGOCIO_ID = DIM_CN.CLASIFICACION_NEGOCIO_ID)
		ELSE NULL END AS 'CLASIFICACION_NEGOCIO',
		--DIA DE LA SEMANA -------------------------------------------
		(SELECT TOP 1 DIM_D2.DIA_DETALLE
			FROM STARSHIP_BI.HECHOS_PEDIDO HP2
			JOIN STARSHIP_BI.DIMENSION_LUGAR DIM_LU2 ON DIM_LU2.LUGAR_ID = HP2.LUGAR_ID
			JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T2 ON DIM_T2.TIEMPO_ID = HP2.TIEMPO_ID
			JOIN STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO DIM_CN2 ON DIM_CN2.CLASIFICACION_NEGOCIO_ID = HP2.CLASIFICACION_NEGOCIO_ID
			---
			JOIN STARSHIP_BI.DIMENSION_DIA DIM_D2 ON DIM_D2.DIA_ID = HP2.DIA_ID
			WHERE 
				DIM_T2.TIEMPO_ID = DIM_T.TIEMPO_ID AND
				DIM_LU2.LUGAR_ID = DIM_LU.LUGAR_ID AND
				DIM_CN2.CLASIFICACION_NEGOCIO_ID = DIM_CN.CLASIFICACION_NEGOCIO_ID
			GROUP BY 
				DIM_D2.DIA_ID,
				DIM_D2.DIA_DETALLE
			ORDER BY
				SUM(HP2.CANTIDAD_PEDIDOS) DESC
		) AS '[ DIA_CON_MAYOR_CANT_PEDIDOS ]',
		--FRANJA HORARIA ----------------------------------------------
		(SELECT TOP 1 (RTRIM(DIM_RH2.RANGO_HORARIO_INI)+' - '+RTRIM(DIM_RH2.RANGO_HORARIO_FIN))
			FROM STARSHIP_BI.HECHOS_PEDIDO HP2
			JOIN STARSHIP_BI.DIMENSION_LUGAR DIM_LU2 ON DIM_LU2.LUGAR_ID = HP2.LUGAR_ID
			JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T2 ON DIM_T2.TIEMPO_ID = HP2.TIEMPO_ID
			JOIN STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO DIM_CN2 ON DIM_CN2.CLASIFICACION_NEGOCIO_ID = HP2.CLASIFICACION_NEGOCIO_ID
			---
			JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO DIM_RH2 ON DIM_RH2.RANGO_HORARIO_ID = HP2.RANGO_HORARIO_ID
			WHERE 
				DIM_T2.TIEMPO_ID = DIM_T.TIEMPO_ID AND
				DIM_LU2.LUGAR_ID = DIM_LU.LUGAR_ID AND
				DIM_CN2.CLASIFICACION_NEGOCIO_ID = DIM_CN.CLASIFICACION_NEGOCIO_ID
			GROUP BY 
				DIM_RH2.RANGO_HORARIO_ID,
				DIM_RH2.RANGO_HORARIO_INI,
				DIM_RH2.RANGO_HORARIO_FIN
			ORDER BY
				SUM(HP2.CANTIDAD_PEDIDOS) DESC
		) AS '[ RANGO_HORARIO_CON_MAYOR_CANT_PEDIDOS ]'
	FROM STARSHIP_BI.HECHOS_PEDIDO HP
	JOIN STARSHIP_BI.DIMENSION_LUGAR DIM_LU ON DIM_LU.LUGAR_ID = HP.LUGAR_ID
	JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T ON DIM_T.TIEMPO_ID = HP.TIEMPO_ID
	JOIN STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO DIM_CN ON DIM_CN.CLASIFICACION_NEGOCIO_ID = HP.CLASIFICACION_NEGOCIO_ID
	GROUP BY
		DIM_T.TIEMPO_ID,
		DIM_T.TIEMPO_ANIO,
		DIM_T.TIEMPO_MES,
		DIM_LU.LUGAR_ID,
		DIM_LU.LUGAR_PROVINCIA_NOMBRE,
		DIM_LU.LUGAR_LOCALIDAD_NOMBRE,
		DIM_CN.CLASIFICACION_NEGOCIO_ID
GO --select * from STARSHIP_BI.VIEW_01_MAYOR_CANTIDAD_DE_PEDIDOS --5597



/*/////////////////////////////////////////////////////////////////////////
Monto total no cobrado por cada local en función de los pedidos
cancelados según el día de la semana y la franja horaria (cuentan como
pedidos cancelados tanto los que cancela el usuario como el local).
*/
CREATE VIEW STARSHIP_BI.VIEW_02_MONTO_TOTAL_NO_COBRADO
AS
	SELECT
		DIM_NEGO.NEGOCIO_ID,
		DIM_NEGO.NEGOCIO_DESCRIPCION AS 'NEGOCIO NOMBRE',
		DIM_DIA.DIA_ID,
		DIM_DIA.DIA_DETALLE,
		DIM_RH.RANGO_HORARIO_ID,
		RTRIM(DIM_RH.RANGO_HORARIO_INI)+' - '+RTRIM(DIM_RH.RANGO_HORARIO_FIN) AS 'RANGO_HORARIO_DETALLE',
		SUM(TOTAL_PEDIDOS) AS '[ MONTO_TOTAL_NO_COBRADO ]'
	FROM STARSHIP_BI.HECHOS_PEDIDO HP
	JOIN STARSHIP_BI.DIMENSION_NEGOCIO DIM_NEGO ON DIM_NEGO.NEGOCIO_ID = HP.NEGOCIO_ID
	JOIN STARSHIP_BI.DIMENSION_DIA DIM_DIA ON DIM_DIA.DIA_ID = HP.DIA_ID
	JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO DIM_RH ON DIM_RH.RANGO_HORARIO_ID = HP.RANGO_HORARIO_ID
	JOIN STARSHIP_BI.DIMENSION_ESTADO_PEDIDO DIM_EST_PED2 ON DIM_EST_PED2.ESTADO_PEDIDO_ID = HP.ESTADO_PEDIDO_ID
			AND DIM_EST_PED2.ESTADO_PEDIDO_DESCRIPCION LIKE '%Cancelado'
	GROUP BY 
		DIM_NEGO.NEGOCIO_ID,
		DIM_NEGO.NEGOCIO_DESCRIPCION,
		DIM_DIA.DIA_ID,
		DIM_DIA.DIA_DETALLE,
		DIM_RH.RANGO_HORARIO_ID,
		RTRIM(DIM_RH.RANGO_HORARIO_INI)+' - '+RTRIM(DIM_RH.RANGO_HORARIO_FIN)
GO --select * from STARSHIP_BI.VIEW_02_MONTO_TOTAL_NO_COBRADO --5354


/*/////////////////////////////////////////////////////////////////////////
Valor promedio mensual que tienen los envíos de pedidos en cada
localidad.
*/
CREATE VIEW STARSHIP_BI.VIEW_03_PROMEDIO_MENSUAL_ENVIOS_PEDIDO
AS
	SELECT
		DIM_LU.LUGAR_ID,
		DIM_LU.LUGAR_LOCALIDAD_NOMBRE AS 'LOCALIDAD',
		DIM_LU.LUGAR_PROVINCIA_NOMBRE AS 'PROVINCIA',
		ISNULL(CAST((SELECT AVG(PROMEDIOS) FROM 
			(SELECT SUM(TOTAL_ENVIO)/SUM(CANTIDAD_EVENTOS) AS PROMEDIOS
			FROM STARSHIP_BI.HECHOS_ENVIO HE2
			JOIN STARSHIP_BI.DIMENSION_EVENTO DIM_EVE2 ON DIM_EVE2.EVENTO_ID = HE2.EVENTO_ID AND DIM_EVE2.EVENTO_DESCRIPCIOIN = 'PEDIDO'
			JOIN STARSHIP_BI.DIMENSION_LUGAR DIM_LU2 ON DIM_LU2.LUGAR_ID = HE2.LUGAR_ID
			JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T2 ON DIM_T2.TIEMPO_ID = HE2.TIEMPO_ID
			WHERE 
				DIM_LU2.LUGAR_ID = DIM_LU.LUGAR_ID
			GROUP BY DIM_T2.TIEMPO_ID) AS XD
		)AS DECIMAL(10,2)),0) AS '[ PROMEDIO_MENSUAL_DE_ENVIOS_PEDIDO ]'
	FROM STARSHIP_BI.HECHOS_ENVIO HE
	JOIN STARSHIP_BI.DIMENSION_LUGAR DIM_LU ON DIM_LU.LUGAR_ID = HE.LUGAR_ID
	GROUP BY 
		DIM_LU.LUGAR_ID,
		DIM_LU.LUGAR_LOCALIDAD_NOMBRE,
		DIM_LU.LUGAR_PROVINCIA_NOMBRE
GO --select * from STARSHIP_BI.VIEW_03_PROMEDIO_MENSUAL_ENVIOS_PEDIDO


/*/////////////////////////////////////////////////////////////////////////
Desvío promedio en tiempo de entrega según el tipo de movilidad, el día
de la semana y la franja horaria.

El desvío debe calcularse en minutos y representa la diferencia entre la
fecha/hora en que se realizó el pedido y la fecha/hora que se entregó en
comparación con los minutos de tiempo estimados.
Este indicador debe tener en cuenta todos los envíos, es decir, sumar tanto
los envíos de pedidos como los de mensajería.
*/
CREATE VIEW STARSHIP_BI.VIEW_04_DESVIO_PROMEDIO_EN_TIEMPO_DE_ENTREGA
AS
	SELECT
		DIM_TMOV.TIPO_MOVILIDAD_ID,
		DIM_TMOV.TIPO_MOVILIDAD_DESCRIPCION AS 'TIPO_MOVILIDAD',
		DIM_DIA.DIA_ID,
		DIM_DIA.DIA_DETALLE AS 'DIA',
		DIM_RHORA.RANGO_HORARIO_ID,
		RTRIM(DIM_RHORA.RANGO_HORARIO_INI)+' - '+RTRIM(DIM_RHORA.RANGO_HORARIO_FIN) AS 'RANGO_HORARIO',
		CAST(AVG(HE.DESVIO/HE.CANTIDAD_EVENTOS) AS DECIMAL(10,4)) AS '[ DEVIO_PROMEDIO_EN_TIEMPO_DE_ENTREGA ]'
	FROM STARSHIP_BI.HECHOS_ENVIO HE
	JOIN STARSHIP_BI.DIMENSION_TIPO_MOVILIDAD DIM_TMOV ON DIM_TMOV.TIPO_MOVILIDAD_ID = HE.TIPO_MOVILIDAD_ID
	JOIN STARSHIP_BI.DIMENSION_DIA DIM_DIA ON DIM_DIA.DIA_ID = HE.DIA_ID
	JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO DIM_RHORA ON DIM_RHORA.RANGO_HORARIO_ID = HE.RANGO_HORARIO_ID
	GROUP BY
		DIM_TMOV.TIPO_MOVILIDAD_ID,
		DIM_TMOV.TIPO_MOVILIDAD_DESCRIPCION,
		DIM_DIA.DIA_ID,
		DIM_DIA.DIA_DETALLE,
		DIM_RHORA.RANGO_HORARIO_ID,
		RTRIM(DIM_RHORA.RANGO_HORARIO_INI)+' - '+RTRIM(DIM_RHORA.RANGO_HORARIO_FIN)
GO --select * from STARSHIP_BI.VIEW_04_DESVIO_PROMEDIO_EN_TIEMPO_DE_ENTREGA


/*/////////////////////////////////////////////////////////////////////////
Monto total de los cupones utilizados por mes en función del rango etario
de los usuarios.
*/
CREATE VIEW STARSHIP_BI.VIEW_05_TOTAL_CUPONES_POR_MES
AS
	SELECT
		DIM_T.TIEMPO_ID,
		DIM_T.TIEMPO_ANIO AS 'ANIO',
		DIM_T.TIEMPO_MES AS 'MES',
		DIM_RE.RANGO_ETARIO_ID,
		RTRIM(DIM_RE.RANGO_ETARIO_INI)+' - '+RTRIM(DIM_RE.RANGO_ETARIO_FIN) AS 'RANGO_ETARIO',
		SUM(TOTAL_CUPONES) AS '[ MONTO_TOTAL_CUPONES ]'
	FROM STARSHIP_BI.HECHOS_PEDIDO HP
	JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T ON DIM_T.TIEMPO_ID = HP.TIEMPO_ID
	JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO DIM_RE ON DIM_RE.RANGO_ETARIO_ID = HP.RANGO_ETARIO_ID
	GROUP BY
		DIM_T.TIEMPO_ID,
		DIM_T.TIEMPO_ANIO,
		DIM_T.TIEMPO_MES,
		DIM_RE.RANGO_ETARIO_ID,
		RTRIM(DIM_RE.RANGO_ETARIO_INI)+' - '+RTRIM(DIM_RE.RANGO_ETARIO_FIN)
GO --select * from STARSHIP_BI.VIEW_05_TOTAL_CUPONES_POR_MES


/*/////////////////////////////////////////////////////////////////////////
Promedio de calificación mensual por local.
*/
CREATE VIEW STARSHIP_BI.VIEW_06_CALIFICACION_PROMEDIO_MENSUAL_POR_LOCAL
AS
	SELECT
		DIM_NEGO.NEGOCIO_ID,
		DIM_NEGO.NEGOCIO_DESCRIPCION,
		(SELECT AVG(PROMEDIO) FROM
			(SELECT SUM(HP2.CALIFICACION_PEDIDOS)/SUM(HP2.CANTIDAD_PEDIDOS) AS 'PROMEDIO'
			FROM STARSHIP_BI.HECHOS_PEDIDO HP2
			JOIN STARSHIP_BI.DIMENSION_TIEMPO DT2 ON DT2.TIEMPO_ID = HP2.TIEMPO_ID
			JOIN STARSHIP_BI.DIMENSION_NEGOCIO DIM_NEGO2 ON DIM_NEGO2.NEGOCIO_ID = HP2.NEGOCIO_ID
			WHERE DIM_NEGO2.NEGOCIO_ID = DIM_NEGO.NEGOCIO_ID) AS AVG_
		) AS '[ CALIFICACION_PROMEDIO_MENSUAL ]'
	FROM STARSHIP_BI.HECHOS_PEDIDO HP
	JOIN STARSHIP_BI.DIMENSION_NEGOCIO DIM_NEGO ON DIM_NEGO.NEGOCIO_ID = HP.NEGOCIO_ID
	GROUP BY
		DIM_NEGO.NEGOCIO_ID,
		DIM_NEGO.NEGOCIO_DESCRIPCION
GO --select * from STARSHIP_BI.VIEW_06_CALIFICACION_PROMEDIO_MENSUAL_POR_LOCAL


/*/////////////////////////////////////////////////////////////////////////
Porcentaje de pedidos y mensajería entregados mensualmente según el
rango etario de los repartidores y la localidad.

Este indicador se debe tener en cuenta y sumar tanto los envíos de pedidos
como los de mensajería.
El porcentaje se calcula en función del total general de pedidos y envíos
mensuales entregados.
*/
CREATE VIEW STARSHIP_BI.VIEW_07_PORCENTAJE_ENVIOS_ENTREGADOS_MENSUALES
AS
	SELECT
		DIM_RE.RANGO_ETARIO_ID,
		RTRIM(DIM_RE.RANGO_ETARIO_INI)+' - '+RTRIM(DIM_RE.RANGO_ETARIO_FIN) AS 'RANGO_ETARIO_REPARTIDORES',
		DIM_L.LUGAR_ID,
		DIM_L.LUGAR_LOCALIDAD_NOMBRE AS 'LOCALIDAD', 
		ISNULL(RTRIM(CAST(ROUND((SELECT AVG(PORCENTAJE) FROM 
			(SELECT
				(
				(SUM(HE2.CANTIDAD_EVENTOS) - 
					(SELECT SUM(HE3.CANTIDAD_EVENTOS) 
					FROM STARSHIP_BI.HECHOS_ENVIO HE3
					JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO DIM_RE3 ON DIM_RE3.RANGO_ETARIO_ID = HE3.RANGO_ETARIO_ID
					JOIN STARSHIP_BI.DIMENSION_LUGAR DIM_L3 ON DIM_L3.LUGAR_ID = HE3.LUGAR_ID
					JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T3 ON DIM_T3.TIEMPO_ID = HE3.TIEMPO_ID
					JOIN STARSHIP_BI.DIMENSION_ESTADO_PEDIDO DIM_EP3 ON DIM_EP3.ESTADO_PEDIDO_ID = HE3.ESTADO_PEDIDO_ID
					JOIN STARSHIP_BI.DIMENSION_ESTADO_ENVIO_MENSAJERIA DIM_EM3 ON DIM_EM3.ESTADO_MENSAJERIA_ID = HE3.ESTADO_MENSAJERIA_ID
					WHERE
						DIM_RE3.RANGO_ETARIO_ID = DIM_RE2.RANGO_ETARIO_ID AND
						DIM_L3.LUGAR_ID = DIM_L2.LUGAR_ID AND
						DIM_T3.TIEMPO_ID = DIM_T2.TIEMPO_ID AND
						(DIM_EP3.ESTADO_PEDIDO_DESCRIPCION LIKE '%Cancelado' OR
						DIM_EM3.ESTADO_MENSAJERIA_DESCRIPCION LIKE '%Cancelado')
					GROUP BY
						DIM_RE3.RANGO_ETARIO_ID,
						DIM_L3.LUGAR_ID,
						DIM_T3.TIEMPO_ID
					)
				)*100
				/SUM(HE2.CANTIDAD_EVENTOS)
				) AS 'PORCENTAJE'
			FROM STARSHIP_BI.HECHOS_ENVIO HE2
			JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO DIM_RE2 ON DIM_RE2.RANGO_ETARIO_ID = HE2.RANGO_ETARIO_ID
			JOIN STARSHIP_BI.DIMENSION_LUGAR DIM_L2 ON DIM_L2.LUGAR_ID = HE2.LUGAR_ID
			JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T2 ON DIM_T2.TIEMPO_ID = HE2.TIEMPO_ID
			WHERE
				DIM_RE2.RANGO_ETARIO_ID = DIM_RE.RANGO_ETARIO_ID AND
				DIM_L2.LUGAR_ID = DIM_L.LUGAR_ID
			GROUP BY
				DIM_RE2.RANGO_ETARIO_ID,
				DIM_L2.LUGAR_ID,
				DIM_T2.TIEMPO_ID
			) AS AVG_
		),0 )AS DECIMAL(10,2)))+' %', '-') AS '[ PORCENTAJE_ENVIOS_ENTREGADOS_MENSUALES ]'
	FROM STARSHIP_BI.HECHOS_ENVIO HE
	JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO DIM_RE ON DIM_RE.RANGO_ETARIO_ID = HE.RANGO_ETARIO_ID
	JOIN STARSHIP_BI.DIMENSION_LUGAR DIM_L ON DIM_L.LUGAR_ID = HE.LUGAR_ID
	GROUP BY
		DIM_RE.RANGO_ETARIO_ID,
		RTRIM(DIM_RE.RANGO_ETARIO_INI)+' - '+RTRIM(DIM_RE.RANGO_ETARIO_FIN),
		DIM_L.LUGAR_ID,
		DIM_L.LUGAR_LOCALIDAD_NOMBRE
GO --select * from STARSHIP_BI.VIEW_07_PORCENTAJE_ENVIOS_ENTREGADOS_MENSUALES order by 3 desc,1,2


/*/////////////////////////////////////////////////////////////////////////
Promedio mensual del valor asegurado (valor declarado por el usuario) de
los paquetes enviados a través del servicio de mensajería en función del
tipo de paquete.
*/
CREATE VIEW STARSHIP_BI.VIEW_08_PROMEDIO_MENSUAL_DEL_VALOR_ASEGURADO
AS
	SELECT
		DIM_TP.TIPO_PAQUETE_ID,
		DIM_TP.TIPO_PAQUETE_DESCRIPCION AS 'TIPO_PAQUETE',
		(SELECT AVG(PROMEDIO) FROM
			(SELECT SUM(HE2.TOTAL_VALOR_ASEGURADO)/SUM(HE2.CANTIDAD_EVENTOS) AS 'PROMEDIO'
			FROM STARSHIP_BI.HECHOS_ENVIO HE2
			JOIN STARSHIP_BI.DIMENSION_TIPO_PAQUETE DIM_TP2 ON DIM_TP2.TIPO_PAQUETE_ID = HE2.TIPO_PAQUETE_ID
			JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T2 ON DIM_T2.TIEMPO_ID = HE2.TIEMPO_ID
			WHERE
				DIM_TP2.TIPO_PAQUETE_ID = DIM_TP.TIPO_PAQUETE_ID
			GROUP BY
				DIM_TP2.TIPO_PAQUETE_ID,
				DIM_T2.TIEMPO_ID) AS AVG_
		) AS '[ PROMEDIO_MENSUAL_DEL_VALOR_ASEGURADO ]'
	FROM STARSHIP_BI.HECHOS_ENVIO HE
	JOIN STARSHIP_BI.DIMENSION_TIPO_PAQUETE DIM_TP ON DIM_TP.TIPO_PAQUETE_ID = HE.TIPO_PAQUETE_ID
	AND DIM_TP.TIPO_PAQUETE_DESCRIPCION <> 'NONE'
	GROUP BY
		DIM_TP.TIPO_PAQUETE_ID,
		DIM_TP.TIPO_PAQUETE_DESCRIPCION
GO --select * from STARSHIP_BI.VIEW_08_PROMEDIO_MENSUAL_DEL_VALOR_ASEGURADO


/*/////////////////////////////////////////////////////////////////////////
Cantidad de reclamos mensuales recibidos por cada local en función del
día de la semana y rango horario.
*/
CREATE VIEW STARSHIP_BI.VIEW_09_CANTIDAD_RECLAMOS_MENSUALES
AS
	SELECT
		DIM_NEGO.NEGOCIO_ID,
		DIM_NEGO.NEGOCIO_DESCRIPCION,
		DIM_D.DIA_ID,
		DIM_D.DIA_DETALLE AS 'DIA',
		DIM_RH.RANGO_HORARIO_ID,
		RTRIM(DIM_RH.RANGO_HORARIO_INI)+' - '+RTRIM(DIM_RH.RANGO_HORARIO_FIN) AS 'RANGO_HORARIO',
		CAST(ROUND((SELECT AVG(PROMEDIO) FROM
			(SELECT SUM(CANTIDAD_RECLAMOS) AS 'PROMEDIO'
			FROM STARSHIP_BI.HECHOS_RECLAMO HR2
			JOIN STARSHIP_BI.DIMENSION_NEGOCIO DIM_NEGO2 ON DIM_NEGO2.NEGOCIO_ID = HR2.NEGOCIO_ID
			JOIN STARSHIP_BI.DIMENSION_DIA DIM_D2 ON DIM_D2.DIA_ID = HR2.DIA_ID
			JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO DIM_RH2 ON DIM_RH2.RANGO_HORARIO_ID = HR2.RANGO_HORARIO_ID
			JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T2 ON DIM_T2.TIEMPO_ID = HR2.TIEMPO_ID
			WHERE
				DIM_NEGO2.NEGOCIO_ID = DIM_NEGO.NEGOCIO_ID AND
				DIM_D2.DIA_ID = DIM_D.DIA_ID AND
				DIM_RH2.RANGO_HORARIO_ID = DIM_RH.RANGO_HORARIO_ID
			GROUP BY
				DIM_T2.TIEMPO_ID) AS AVG_
		),0) AS DECIMAL(10)) AS '[ CANTIDAD_RECLAMOS_MENSUALES ]'
	FROM STARSHIP_BI.HECHOS_RECLAMO HR
	JOIN STARSHIP_BI.DIMENSION_NEGOCIO DIM_NEGO ON DIM_NEGO.NEGOCIO_ID = HR.NEGOCIO_ID
	JOIN STARSHIP_BI.DIMENSION_DIA DIM_D ON DIM_D.DIA_ID = HR.DIA_ID
	JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO DIM_RH ON DIM_RH.RANGO_HORARIO_ID = HR.RANGO_HORARIO_ID
	GROUP BY
		DIM_NEGO.NEGOCIO_ID,
		DIM_NEGO.NEGOCIO_DESCRIPCION,
		DIM_D.DIA_ID,
		DIM_D.DIA_DETALLE,
		DIM_RH.RANGO_HORARIO_ID,
		RTRIM(DIM_RH.RANGO_HORARIO_INI)+' - '+RTRIM(DIM_RH.RANGO_HORARIO_FIN)
GO --select * from STARSHIP_BI.VIEW_09_CANTIDAD_RECLAMOS_MENSUALES order by 1,2 --21


/*/////////////////////////////////////////////////////////////////////////
Tiempo promedio de resolución de reclamos mensual según cada tipo de
reclamo y rango etario de los operadores.
El tiempo de resolución debe calcularse en minutos y representa la
diferencia entre la fecha/hora en que se realizó el reclamo y la fecha/hora
que se resolvió.
*/
CREATE VIEW STARSHIP_BI.VIEW_10_TIEMPO_PROMEDIO_MENSUAL_RESOL_RECLAMOS
AS
	SELECT
		DIM_TR.TIPO_RECLAMO_ID,
		DIM_TR.TIPO_RECLAMO_DESCRIPCION AS 'TIPO_RECLAMO',
		DIM_RE.RANGO_ETARIO_ID,
		RTRIM(DIM_RE.RANGO_ETARIO_INI)+' - '+RTRIM(DIM_RE.RANGO_ETARIO_FIN) AS 'RANGO_ETARIO',
		(SELECT AVG(PROMEDIO) FROM
			(SELECT SUM(HR2.TIEMPO_RESOLUCION)/SUM(HR2.CANTIDAD_RECLAMOS) AS 'PROMEDIO'
			FROM STARSHIP_BI.HECHOS_RECLAMO HR2
			JOIN STARSHIP_BI.DIMENSION_TIPO_RECLAMO DIM_TR2 ON DIM_TR2.TIPO_RECLAMO_ID = HR2.TIPO_RECLAMO_ID
			JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO DIM_RE2 ON DIM_RE2.RANGO_ETARIO_ID = HR2.RANGO_ETARIO_ID
			JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T2 ON DIM_T2.TIEMPO_ID = HR2.TIEMPO_ID
			WHERE
				DIM_TR2.TIPO_RECLAMO_ID = DIM_TR.TIPO_RECLAMO_ID AND
				DIM_RE2.RANGO_ETARIO_ID = DIM_RE.RANGO_ETARIO_ID
			GROUP BY
				DIM_T2.TIEMPO_ID) AS AVG_
		) AS '[ TIEMPO_PROMEDIO_MENSUAL_RESOL_RECLAMOS ]'
	FROM STARSHIP_BI.HECHOS_RECLAMO HR
	JOIN STARSHIP_BI.DIMENSION_TIPO_RECLAMO DIM_TR ON DIM_TR.TIPO_RECLAMO_ID = HR.TIPO_RECLAMO_ID
	JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO DIM_RE ON DIM_RE.RANGO_ETARIO_ID = HR.RANGO_ETARIO_ID
	GROUP BY
		DIM_TR.TIPO_RECLAMO_ID,
		DIM_TR.TIPO_RECLAMO_DESCRIPCION,
		DIM_RE.RANGO_ETARIO_ID,
		RTRIM(DIM_RE.RANGO_ETARIO_INI)+' - '+RTRIM(DIM_RE.RANGO_ETARIO_FIN)
GO --select * from STARSHIP_BI.VIEW_10_TIEMPO_PROMEDIO_MENSUAL_RESOL_RECLAMOS


/*/////////////////////////////////////////////////////////////////////////
Monto mensual generado en cupones a partir de reclamos.
*/
CREATE VIEW STARSHIP_BI.VIEW_11_MONTO_MENSUAL_EN_CUPONES_DE_RECLAMO
AS
	SELECT 
		DIM_T.TIEMPO_ID,
		DIM_T.TIEMPO_ANIO AS 'ANIO',
		DIM_T.TIEMPO_MES AS 'MES',
		SUM(HR.MONTO_EN_CUPONES) AS '[ MONTO_MENSUAL_EN_CUPONES_DE_RECLAMO ]'
	FROM STARSHIP_BI.HECHOS_RECLAMO HR
	JOIN STARSHIP_BI.DIMENSION_TIEMPO DIM_T ON DIM_T.TIEMPO_ID = HR.TIEMPO_ID
	GROUP BY
		DIM_T.TIEMPO_ID,
		DIM_T.TIEMPO_ANIO,
		DIM_T.TIEMPO_MES
GO --select * from STARSHIP_BI.VIEW_11_MONTO_MENSUAL_EN_CUPONES_DE_RECLAMO