CREATE VIEW STARSHIP_BI.view_dia_hora_localidad_mas_pedidos
AS
    SELECT TOP (1)
        DT.MES,
        DT.ANIO,
        DD.DIA_DETALLE,
        DRH.RANGO_HORARIO_INI,
        DRH.RANGO_HORARIO_FIN,
        DL.LUGAR_LOCALIDAD_NOMBRE,
        DCN.CLASIFICACION_NEGOCIO_CATEGORIA,
        HV.HV_CANTIDAD_PEDIDOS

	FROM STARSHIP_BI.HECHOS_VENTA AS HV

    JOIN STARSHIP_BI.DIMENSION_DIA AS DD ON DD.DIA_ID = HV.HV_DIA
    JOIN STARSHIP_BI.DIMENSION_TIEMPO AS DT ON HV.HV_TIEMPO = DT.TIMEPO_ID
    JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO ON HV.HV_RANGO_HORARIO = DRH.RANGO_HORARIO_ID
    JOIN STARSHIP_BI.DIMENSION_LUGAR AS DL ON DL.LUGAR_ID = HV.HV_LUGAR
    JOIN STARSHIP_BI.DIMENSION_CLASIFICACION_NEGOCIO AS DCN ON DCN.CLASIFICACION_NEGOCIO_ID = HV.HV_HV_CLASIFICACION_NEGOCIO
    
    GROUP BY DT.MES, DT.ANIO, DD.DIA_DETALLE, DRH.RANGO_HORARIO_INI, DRH.RANGO_HORARIO_FIN,
    DL.LUGAR_LOCALIDAD_NOMBRE, DCN.CLASIFICACION_NEGOCIO_CATEGORIA

    ORDER BY HV.HV_CANTIDAD_PEDIDOS DESC
GO

---

CREATE VIEW STARSHIP_BI.view_total_no_cobrado
AS
    SELECT
        SUM(),
        DD.DIA_DETALLE,
        DRE.RANGO_EDAD_INI,
        DRE.RANGO_EDAD_FIN,
        DEP.ESTADO_PEDIDO_DESCRIPCION

	FROM STARSHIP_BI. AS H

    JOIN STARSHIP_BI.DIMENSION_DIA AS DD ON DD.DIA_ID = ._DIA

    JOIN STARSHIP_BI.DIMENSION_NEGOCIO AS DN ON DN.NEGOCIO_ID = ._NEGOCIO

    JOIN STARSHIP_BI.DIMENSION_ESTADO_PEDIDO AS DEP ON DEP.ESTADO_PEDIDO_ID = ._ESTADO_PEDIDO

    JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO AS DRE ON DRE.RANGO_ETARIO_ID = 

    WHERE DEP.ESTADO_PEDIDO_DESCRIPCION = "" --- TODO PONER "CANCELADO", no se como aparece en DB

    GROUP BY DD.DIA_DETALLE, DRE.RANGO_EDAD_INI, DRE.RANGO_EDAD_FIN
	

GO

---

CREATE VIEW STARSHIP_BI.view_promedio_mensual_envio
AS
    SELECT
        monto total envios / cantidad envios,
        DL.LUGAR_NOMBRE, --- LOCALIDAD
        DT.MES,
        DT.ANIO

	FROM STARSHIP_BI. AS H

    JOIN STARSHIP_BI.DIMENSION_TIEMPO AS DT ON ._TIEMPO = DT.TIEMPO_ID

    JOIN STARSHIP_BI.DIMENSION_LUGAR AS DL ON DL.LUGAR_ID = ._LUGAR

    GROUP BY DL.LUGAR_NOMBRE, DT.MES, DT.ANIO
GO

---

CREATE VIEW STARSHIP_BI.view_desvio_tiempo_promedio
AS
    SELECT
        DTM.TIPO_MOVILIDAD_DESCRIPCION,
        DD.DIA_DETALLE,
        DRE.RANGO_HORARIO_INI,
        DRE.RANGO_HORARIO_FIN,
        AVG(DESVIO) --- MINUTOS, DIFERENCIA FECHA/HORAS, COMPARACION CON ESTIMADO
	
    FROM STARSHIP_BI.HECHOS_ENTREGA AS HE

    JOIN STARSHIP_BI.DIMENSION_TIPO_MOVILIDAD AS DTM ON DTM.TIPO_MOVILIDAD_ID = HE.HE_TIPO_MOVILIDAD
    JOIN STARSHIP_BI.DIMENSION_DIA AS DD ON DD.DIA_ID = HE.HE_DIA
    JOIN STARSHIP_BI.DIMENSION_RANGO_HORARIO AS DRE ON DRE.RANGO_HORARIO_ID = HE.RANGO_HORARIO
    
    GROUP BY DTM.TIPO_MOVILIDAD_DESCRIPCION, DD.DIA_DETALLE, FRANJA_HORARIA
GO

---

CREATE VIEW STARSHIP_BI.view_total_cupones_edad
AS
    SELECT
        DT.MES,
        DT.ANIO,
        DRE.RANGO_ETARIO_INI, --- USUARIOS
        DRE.RANGO_ETARIO_FIN,
        HD.HD_MONTO_CUPONES

	FROM STARSHIP_BI.HECHOS_DESCUENTO AS HD

    JOIN STARSHIP_BI.DIMENSION_TIEMPO AS DT ON HD.HD_TIEMPO = DT.TIEMPO_ID
    JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO AS DRE ON HD.HD_RANGO_ETARIO = DRE.RANGO_ETARIO_ID
    
    GROUP BY DT.MES, DT.ANIO, DRE.RANGO_ETARIO_INI, DRE.RANGO_ETARIO_FIN
GO

---

CREATE VIEW STARSHIP_BI.view_calificacion_promedio_local
AS
    SELECT
        DT.MES,
        DT.ANIO,
        DN.NEGOCIO_DESCRIPCION,
        HC_CALIFICACION_NEGOCIO_TOTAL

	FROM STARSHIP_BI.HECHOS_COMPRA AS HC

    JOIN STARSHIP_BI.DIMENSION_TIEMPO AS DT ON HC.HC_TIEMPO = DT.TIEMPO_ID
    JOIN STARSHIP_BI.DIMENSION_NEGOCIO DN ON HC.HC_NEGOCIO = DN.NEGOCIO_ID
    
    GROUP BY DT.MES, DT.ANIO, DN.NEGOCIO_DESCRIPCION
GO

---

CREATE VIEW STARSHIP_BI.view_promedio_pedido_mensajeria
AS
    SELECT
        DRE.RANGO_HETARIO_INI, --- REPARTIDORES
        DRE.RANGO_HETARIO_FIN,
        DN.NEGOCIO_DESCRIPCION
	
    FROM STARSHIP_BI.HECHOS_ENTREGA AS HE

    JOIN STARSHIP_BI.DIMENSION_NEGOCIO DN ON HE.HE_NEGOCIO = DN.NEGOCIO_ID

    JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO AS DRE ON DRE.RANGO_ETARIO_ID = HE.HE_RANGO_ETARIO

    GROUP BY DRE.RANGO_HETARIO_INI, DRE.RANGO_HETARIO_FIN,
        DN.NEGOCIO_DESCRIPCION


GO

---

CREATE VIEW STARSHIP_BI.view_promedio_mensual_asegurado
AS
    SELECT
        DTP.TIPO_PAQUETE_DESCRIPCION,
        HE.HE_VALOR_ASEGURADO_TOTAL / HE.HE_

	FROM STARSHIP_BI.HECHOS_ENTREGA AS HE

    JOIN STARSHIP_BI.DIMENSION_TIPO_PAQUETE AS DTP ON DTP.TIPO_PAQUETE_ID = HE.HE_TIPO_PAQUETE
    
    GROUP BY DTP.TIPO_PAQUETE_DESCRIPCION
	
GO

---

CREATE VIEW STARSHIP_BI.view_cantidad_reclamos
AS
    SELECT
        HR.HR_CANTIDAD_RECLAMOS,
        DT.MES,
        DT.ANIO,
        DN.NEGOCIO_DESCRIPCION,
        DD.DIA_DETALLE,
        DRH.RANGO_HORARIO_INI,
        DRH.RANGO_HORARIO_FIN

	FROM STARSHIP_BI.HECHOS_RECLAMO AS HR

    JOIN STARSHIP_BI.DIMENSION_TIEMPO AS DT ON HR.HR_TIEMPO = DT.TIEMPO_ID
    JOIN STARSHIP_BI.DIMENSION_DIA AS DD ON DD.DIA_ID = HR.HR_DIA
    JOIN STARSHIP_BI.DIMENSION_NEGOCIO DN ON HR.HR_NEGOCIO = DN.NEGOCIO_ID
    JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO AS DRE ON HR.HR_RANGO_ETARIO = DRE.RANGO_ETARIO_ID
    
    GROUP BY DT.MES, DT.ANIO, DN.NEGOCIO_DESCRIPCION, DD.DIA_DETALLE,
        DRH.RANGO_HORARIO_INI, DRH.RANGO_HORARIO_FIN
GO

---

CREATE VIEW STARSHIP_BI.view_tiempo_promedio_resolucion
AS
    SELECT
        AVG(TIEMPOSOLUCION), --- MINUTOS, DIFERENCIA DE HORAS, DEBERIAMOS AGREGAR A DIMENSION CREO
        DTR.TIPO_RECLAMO_DESCRIPCION,
        DRE.RANGO_ETARIO_INI, --- OPERADOR
        DRE.RANGO_ETARIO_FIN

    FROM STARSHIP_BI.HECHOS_RECLAMO AS HR

    JOIN STARSHIP_BI.DIMENSION_RANGO_ETARIO AS DRE ON HR.HR_RANGO_ETARIO = DRE.RANGO_ETARIO_ID
    JOIN STARSHIP_BI.DIMENSION_TIPO_RECLAMO AS DTR ON DTR.TIPO_RECLAMO_ID = HR.HR_TIPO_RECLAMO
    
    
    GROUP BY DTR.TIPO_RECLAMO_DESCRIPCION, DRE.RANGO_ETARIO_INI, DRE.RANGO_ETARIO_FIN
GO

---

CREATE VIEW STARSHIP_BI.view_monto_mensual_cupones_reclamo
AS
    SELECT
        HD.HD_MONTO_CUPONES,
        DT.MES,
        DT.ANIO

	FROM STARSHIP_BI.HECHOS_DESCUENTO AS HD

    JOIN STARSHIP_BI.DIMENSION_TIEMPO AS DT ON HD.HD_TIEMPO = DT.TIEMPO_ID
    GROUP BY DT.MES, DT.ANIO
GO